### PR TITLE
Switch to bcryptjs and make password comparison async

### LINKED ISSUE #982: Raspberry Pi 2 issues with login in private mode
I tried today to install TheLounge on my raspberry pi. Unfortunately, the private mode did not work, the public without user management worked fine. After some digging into the code I think I found the culprit to be the bcrypt function call. My guess is that the pi is not fast enough in calculating the hashes and therefore nodeJS throws a time-out as during the login the CPU is at 100%. 

It does not go beyond: https://github.com/thelounge/lounge/blob/c409328ddf38db3b421c61bf2f688317f8e07f9d/src/server.js#L270

Hardcoding the return value to `return true` lets me use TheLounge without further issues. 

I tried reducing the rounds of bcrypt [here](https://github.com/thelounge/lounge/blob/c409328ddf38db3b421c61bf2f688317f8e07f9d/src/helper.js#L124) to as low as 3 but it did not help.

Node.JS Version: v6.10.0
NPM Version 3.10.10
TheLounge Version: v2.2.2 - 2017-03-13
Raspberry Pi 2 

I wrote this issue on request of @MaxLeiter

### PR DESCRIPTION
**Pull request by rockhouse**
Closes #982 

Changed to faster brcypt implementation (brcyptjs) for better performance and made the compare call async so it does not timeout anymore. The check still takes ages on resource constraint devices as on the older models of the raspberry pi but it is usable now, you just need a little patience ;)

Performance comparison of the different bcrypt implementations can be found here: https://github.com/thelounge/lounge/pull/983

### CODE REVIEW

File: src/helper.js [hunk 1]
```diff
@@ -21,6 +21,7 @@ var Helper = {
 	password: {
 		hash: passwordHash,
 		compare: passwordCompare,
```
Comment (xPaw) [inline src/helper.js]: Instead of creating separate async method, just update all the code to use async code.

File: src/server.js [hunk 2]
```diff
@@ -354,3 +355,4 @@ function auth(data) {
 		}
 	}
 }
+
```
Comment (astorije) [inline src/server.js]: Could you remove this, please? :)

File: src/server.js [hunk 3]
```diff
@@ -267,19 +267,20 @@ function localAuth(client, user, password, callback) {
...
-
-	return callback(result);
+			client.setPassword(hash, function(success) {
+				if (success) {
+					log.info(`User ${colors.bold(client.name)} logged in and their hashed password has been updated to match new security requirements`);
+				}
+			});
+		}
+		callback(matching);
+	}, (error) => log.error(`Error while checking users password. Error: ${error}`));
```
Comment (astorije) [inline src/server.js]: No need for parentheses around `error`, unless we set up ESLint to be strict like that.

File: src/helper.js (hunk 1 above)
Comment (rockhouse) [inline src/helper.js]: Done

File: test/tests/passwords.js [hunk 4]
```diff
@@ -9,15 +9,26 @@ describe("Client passwords", function() {
...
 		let comparedPassword = Helper.password.compare(inputPassword, "$2a$11$zrPPcfZ091WNfs6QrRHtQeUitlgrJcecfZhxOFiQs0FWw7TN3Q1oS");
+		comparedPassword.then((result) => {
+			expect(result).to.be.true;
+		});
+	});
 
-		expect(comparedPassword).to.be.true;
+	it("hashed password should not match", function() {
+		// Generated with third party tool to test implementation
+		let comparedPassword = Helper.password.compare(inputPassword, "123");
```
Comment (xPaw) [inline test/tests/passwords.js]: I would test against a real hash with a letter difference.

**Comment by astorije** [comment]
FYI I'll give this one more try before merging.

File: test/tests/passwords.js [hunk 5]
```diff
@@ -9,15 +9,26 @@ describe("Client passwords", function() {
 	it("hashed password should match", function() {
 		// Generated with third party tool to test implementation
 		let comparedPassword = Helper.password.compare(inputPassword, "$2a$11$zrPPcfZ091WNfs6QrRHtQeUitlgrJcecfZhxOFiQs0FWw7TN3Q1oS");
+		comparedPassword.then((result) => {
+			expect(result).to.be.true;
+		});
```
Comment (astorije) [inline test/tests/passwords.js]: Actually, this doesn't test anything. Whether you test against `true` or `false`, it passes.
With promises, you need to do `return comparedPassword.then(...);`.

Alternative will be to use `chai-as-promised` to be able to do `return expect(comparedPassword).to.eventually.be.true;` but we will add that later, not worth doing it for 3 tests only :)

File: test/tests/passwords.js (hunk 4 above)
Comment (astorije) [inline test/tests/passwords.js]: I did this in my extra commit (not a single-letter difference but still).

File: src/server.js [hunk 6]
```diff
@@ -267,19 +273,22 @@ function localAuth(client, user, password, callback) {
...
 	}
 
-	var result = Helper.password.compare(password, client.config.password);
-
-	if (result && Helper.password.requiresUpdate(client.config.password)) {
-		var hash = Helper.password.hash(password);
+	Helper.password
+		.compare(password, client.config.password)
+		.then(matching => {
+			if (Helper.password.requiresUpdate(client.config.password)) {
```
Comment (xPaw) [inline src/server.js]: Note from the future, this `if` check missed `matching` comparison and introduced a security vuln.

Comment (dgw) [inline src/server.js]: April Fools security!
