### PR TITLE
Fix away message disappearing

### LINKED ISSUE #1102: awayMessage setting cleared on start
After setting either a network or user-wide `awayMessage` in the user config file and starting lounge, the string is cleared and set back to `""`.

### PR DESCRIPTION
**Pull request by xPaw**
Closes #1102

### CODE REVIEW

File: src/client.js [hunk 1]
```diff
@@ -494,6 +493,8 @@ Client.prototype.clientAttach = function(socketId) {
 		});
 	}
 
+	client.attachedClients[socketId] = client.lastActiveChannel;
+
```
Comment (astorije) [inline src/client.js]: > 18:13	**astorije**	Just curious, why did you move this?
> 18:13	**xPaw**	look at line 487
> 18:14	**xPaw**	it added to array, then compared to see if size of array is 0, which it would be 1
> 18:14	**xPaw**	I could change the comparison to 1, or move assignment
