### PR TITLE
Handle stderr when using edit or config command, fixes #164

### LINKED ISSUE #164: Broken edit CLI command
```js
$ ./index.js edit testuser

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

### PR DESCRIPTION
**Pull request by MaxLeiter**

### CODE REVIEW

**Comment by astorije** [comment]
Not blocking v2.0.0 release, `do not merge` until then.

File: src/command-line/config.js [hunk 1]
```diff
@@ -6,9 +6,12 @@ program
 	.command("config")
 	.description("Edit config: " + Helper.CONFIG_PATH)
 	.action(function() {
-		child.spawn(
-			process.env.EDITOR || "vi",
+		var child_spawn = child.spawn(
+			process.env.EDITOR || "vi" || "nano",
```
Comment (xPaw) [inline src/command-line/config.js]: Your ` || "nano"` addition doesn't make much sense, as the `vi` fallback is for the `EDITOR` being `undefined`.

Comment (MaxLeiter) [inline src/command-line/config.js]: In case vi isn't present, we should try nano. @astorije's idea

Comment (MaxLeiter) [inline src/command-line/config.js]: Should be fixed now

File: src/command-line/config.js [hunk 2]
```diff
@@ -6,9 +6,12 @@ program
...
 	.description("Edit config: " + Helper.CONFIG_PATH)
 	.action(function() {
-		child.spawn(
+		var child_spawn = child.spawn(
 			process.env.EDITOR || "vi",
 			[Helper.CONFIG_PATH],
 			{stdio: "inherit"}
 		);
+		child_spawn.on("error", function() {
+			log.error("$EDITOR is not set, and vi was not found.");
```
Comment (xPaw) [inline src/command-line/config.js]: What I would do is print `Helper.CONFIG_PATH` here so that users can easily edit the file in their favourite editor.

Comment (MaxLeiter) [inline src/command-line/config.js]: Fingers crossed :+1:

File: src/command-line/edit.js [hunk 3]
```diff
@@ -12,9 +12,12 @@ program
...
 			return;
 		}
-		child.spawn(
+		var child_spawn = child.spawn(
 			process.env.EDITOR || "vi",
 			[Helper.getUserConfigPath(name)],
 			{stdio: "inherit"}
 		);
+		child_spawn.on("error", function() {
+			log.error("Unable to open " + Helper.CONFIG_PATH + ". $EDITOR is not set, and vi was not found.");
```
Comment (MaxLeiter) [inline src/command-line/edit.js]: Changed to Helper.getUserConfigPath(name)

**Comment by astorije** [comment]
@xPaw, against the idea of falling back to nano if `vi` isn't found? Not the `vi || nano` thing, sorry I missed that, but in general. It seems to me like most things that open an editor on Unix will default do `nano` if `$EDITOR` isn't set (like git). No strong opinion though, just poking around.

**Comment by xPaw** [comment]
@astorije I don't know which editor is more commonly preinstalled, but I am fine with changing `vi` to `nano` for the fallback.

**Comment by astorije** [comment]
I was actually suggesting both, but maybe a bad idea. I don't care which one really, as long as the default is sensible. Let's go with that for now, changing default editor would be a different PR anyway, sorry for shifting focus.
