### PR TITLE
Fix crash when hostname is changed in lockNetwork mode

### LINKED ISSUE #2040: Crash when hostname is changed in lockNetwork mode
Occurred in demo, unsure of cause

```
2018-01-29 06:32:04 [INFO] Available at http://:::1000/ in public mode
/lounge-demo/src/models/chan.js:102
        irc.network.options.PREFIX.forEach((prefix, index) => {
           ^

TypeError: Cannot read property 'network' of null
    at Chan.getSortedUsers (/root/lounge-demo/src/models/chan.js:102:5)
    at Client.names (/root/lounge-demo/src/client.js:513:22)
    at Socket.<anonymous> (/root/lounge-demo/src/server.js:367:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at /root/lounge-demo/node_modules/socket.io/lib/socket.js:513:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### PR DESCRIPTION
**Pull request by xPaw**
Fixes #2040

### CODE REVIEW

File: src/client.js [hunk 1]
```diff
@@ -224,7 +224,7 @@ Client.prototype.connect = function(args) {
 
 	if (config.lockNetwork) {
 		// This check is needed to prevent invalid user configurations
-		if (args.host && args.host.length > 0 && args.host !== config.defaults.host) {
+		if (!Helper.config.public && args.host && args.host.length > 0 && args.host !== config.defaults.host) {
```
Comment (xPaw) [inline src/client.js]: Servers can come from user configuration only in private mode, so in public mode we can just enforce it.

**Comment by MaxLeiter** [comment]
👍
