### PR TITLE
Date separator fixes

### LINKED ISSUE #763: Date-separator not being removed when it should sometimes
When a 'new messages' marker is at the top of the screen, followed by a date-marker, and the 'show more' button is pressed, the date marker should be removed and inserted at the correct place. Instead it is not, because it only checks the first element after the show-more button if it is a date-marker.

### PR DESCRIPTION
**Pull request by stepie22**
Fixes #763 and #760; I decided to do this in one pr since both are so small fixes. 

For #763 an extra check was added for the new-messages marker and skips it

For #760 I added the reported time, if that was not available, the current time

### CODE REVIEW

File: src/plugins/irc-events/link.js [hunk 1]
```diff
@@ -32,6 +32,7 @@ module.exports = function(irc, network) {
 		var msg = new Msg({
 			self: data.nick === irc.user.nick,
 			type: Msg.Type.TOGGLE,
+			time: data.time || new Date().getTime(),
```
Comment (xPaw) [inline src/plugins/irc-events/link.js]: Msg handles the fallback

Comment (stepie22) [inline src/plugins/irc-events/link.js]: ah, will remove that part then

File: client/js/lounge.js [hunk 2]
```diff
@@ -420,9 +420,12 @@ $(function() {
...
 		// Remove the date-change marker we put at the top, because it may
 		// not actually be a date change now
-		var firstChild = $(chan).children().eq(0);
-		if (firstChild.attr("class") === "date-marker") {
-			firstChild.remove();
+		var children = $(chan).children();
+		if (children.eq(0).attr("class") === "date-marker") { // Check top most child
+			children.eq(0).remove();
+		} else if (children.eq(0).attr("class") === "unread-marker" && children.eq(1).attr("class") === "date-marker") {
+			// Otherwise the date-marker would get 'stuck' because of the new-massages marker
```
Comment (MaxLeiter) [inline client/js/lounge.js]: slight nit-pick: `new-massages` -> `new-message`

**Comment by MaxLeiter** [comment]
Am just going to mention this here: once the client can access npm packages, we can use moments .calender() to create fuzzy time stamps (i.e. "Yesterday")

File: client/js/lounge.js [hunk 3]
```diff
@@ -420,9 +420,12 @@ $(function() {
 
 		// Remove the date-change marker we put at the top, because it may
 		// not actually be a date change now
-		var firstChild = $(chan).children().eq(0);
-		if (firstChild.attr("class") === "date-marker") {
-			firstChild.remove();
+		var children = $(chan).children();
+		if (children.eq(0).attr("class") === "date-marker") { // Check top most child
```
Comment (YaManicKill) [inline client/js/lounge.js]: Ah wait, can you use jquery's hasClass instead? Because this will only give oyu 1 of the classes, which means that it could create bugs in the future if the date marker ends up having more than 1 class on it.

https://api.jquery.com/hasclass/

File: client/js/lounge.js [hunk 4]
```diff
@@ -420,9 +420,12 @@ $(function() {
...
+			children.eq(0).remove();
+		} else if (children.eq(0).attr("class") === "unread-marker" && children.eq(1).attr("class") === "date-marker") {
```
Comment (YaManicKill) [inline client/js/lounge.js]: Same here

**Comment by stepie22** [comment]
Err. @astorije didn't this need to be squashed? I am away for a bit so I can't do it, but pretty sure there is an option for you guys to do so. Referring to the last two commits

**Comment by astorije** [comment]
Argh, I suck, I meant for it then forgot. Too late now, sorry git history!
