### PR TITLE
Fix date-marker not being removed on loading new messages

### LINKED ISSUE #763: Date-separator not being removed when it should sometimes
When a 'new messages' marker is at the top of the screen, followed by a date-marker, and the 'show more' button is pressed, the date marker should be removed and inserted at the correct place. Instead it is not, because it only checks the first element after the show-more button if it is a date-marker.

### PR DESCRIPTION
**Pull request by PolarizedIons**
Fixes #763 again. Affects mastrer (5eb5b99). This is caused by 648cfd12, where @astorije put it inside a container, but didn't update the class we searched for.

What it currently looks like:

Expected behavior:

### CODE REVIEW

**Comment by PolarizedIons** [comment]
err. Now yes :)

**Comment by xPaw** [comment]
Looking at your gifts, looks like the viewport jumps a little when content loads now.

**Comment by PolarizedIons** [comment]
This is the behavior for bc5b03d, before this broke. Not really sure how to fix it either, tbh.

**Comment by bews** [comment]
Current master.  Does this PR fix this too?

**Comment by PolarizedIons** [comment]
Pushed the changes @xPaw, not as hard as I though :smile: 


@bews if those are "stuck" at the top (instead of being caused by join/parts being hidden), then yes, this should fix that.

File: client/js/lounge.js [hunk 1]
```diff
@@ -472,16 +472,19 @@ $(function() {
...
+		} else if (children.eq(0).hasClass("unread-marker") && children.eq(1).hasClass("date-marker-container")) {
+			// Check for unread-marker too - oherwise the date-marker would get 'stuck' because of the new-message marker
+			dateMarkerHeight = children.eq(1).height();
 			children.eq(1).remove();
 		}
 
 		// get the scrollable wrapper around messages
 		var scrollable = chan.closest(".chat");
-		var heightOld = chan.height();
+		var heightOld = chan.height() + dateMarkerHeight; // Add the date marker's height because it was already removed
```
Comment (xPaw) [inline client/js/lounge.js]: Why don't you just get the height before removing the date marker?

Comment (PolarizedIons) [inline client/js/lounge.js]: I guess I was trying to not assume anything, but it is a guarantee that there will be one at the top, so thanks. Moved calculating the height to before I remove it.

File: client/js/lounge.js [hunk 2]
```diff
@@ -469,21 +469,21 @@ $(function() {
...
+
 		// Remove the date-change marker we put at the top, because it may
 		// not actually be a date change now
 		var children = $(chan).children();
-		if (children.eq(0).hasClass("date-marker")) { // Check top most child
+		if (children.eq(0).hasClass("date-marker-container")) { // Check top most child
 			children.eq(0).remove();
-		} else if (children.eq(0).hasClass("unread-marker") && children.eq(1).hasClass("date-marker")) {
-			// Otherwise the date-marker would get 'stuck' because of the new-message marker
+		} else if (children.eq(0).hasClass("unread-marker") && children.eq(1).hasClass("date-marker-container")) {
```
Comment (xPaw) [inline client/js/lounge.js]: Should that first one check for container too?

Comment (PolarizedIons) [inline client/js/lounge.js]: Hmm. I guess it isn't needed, because there will never be normal messages at index 0

**Comment by astorije** [comment]
Unfortunately, I noticed this is still a bug in `v2.3.0-rc.1` :(

date-marker-bug

@PolarizedIons, do you think you could take a look?

**Comment by PolarizedIons** [comment]
Ah whoops, simple mistake, though I wish I would stop making them in PR's :\

**Comment by astorije** [comment]
It's ok, we all do, and we caught this before releasing :)
