### PR TITLE
Fix issue with falsey user options getting overridden by truthy defaults

### LINKED ISSUE #1420: "true" default options can override user settings
How to reproduce:

* Go into options
* See that "Auto-expand websites" is checked
* Uncheck
* Refresh page
* Go into options

What should happen: auto-expand websites should still be unchecked
What actually happens: auto-expand websites is checked again

It's due to [this change](https://github.com/thelounge/lounge/commit/b508783101dfc979e92221a884f87812b27633b7#diff-03ed49e301a4e588ec406bc5aace2a02R31) where it will only set the user option if it is truthy, and so if the default is truthy and the user's option is falsy, it will use the default.

We should have an undefined check instead.

### PR DESCRIPTION
**Pull request by YaManicKill**
Fixes #1420

### CODE REVIEW

File: client/js/options.js [hunk 1]
```diff
@@ -25,14 +25,16 @@ const options = {
...
+let userOptions = JSON.parse(storage.get("settings")) || {};
 
 for (const key in options) {
-	if (userOptions[key]) {
+	if (userOptions[key] !== undefined) {
 		options[key] = userOptions[key];
 	}
 }
 
+userOptions = null;
```
Comment (astorije) [inline client/js/options.js]: I get the change above, but why this one?

Comment (xPaw) [inline client/js/options.js]: Free memory.
