### PR TITLE
Fill in prefixLookup on network initialization

### LINKED ISSUE #644: Crash on prefix lookup in names, if server doesn't provide PREFIX server option.
Running Node v6 and latest lounge installed via npm. I have znc bouncer connected to `irc.juggler.jp:6667`, the network codepage is ISO-2022-JP, but znc converts it to UTF-8 for clients. znc is joined to single channel `#ロシア`.

After adding connection to this znc in lounge, the lounge crashes with:
```
Sep 26 20:59:44 kourindou lounge[29495]: /usr/lib/node_modules/thelounge/src/plugins/irc-events/names.js:17
Sep 26 20:59:44 kourindou lounge[29495]:                                 user.mode = network.prefixLookup[user.mode];
Sep 26 20:59:44 kourindou lounge[29495]:                                                                 ^
Sep 26 20:59:44 kourindou lounge[29495]: TypeError: Cannot read property 'o' of undefined
Sep 26 20:59:44 kourindou lounge[29495]:     at /usr/lib/node_modules/thelounge/src/plugins/irc-events/names.js:17:37
Sep 26 20:59:44 kourindou lounge[29495]:     at arrayEach (/usr/lib/node_modules/thelounge/node_modules/lodash/lodash.js:498:11)
Sep 26 20:59:44 kourindou lounge[29495]:     at Function.forEach (/usr/lib/node_modules/thelounge/node_modules/lodash/lodash.js:8494:11)
Sep 26 20:59:44 kourindou lounge[29495]:     at IrcClient.<anonymous> (/usr/lib/node_modules/thelounge/src/plugins/irc-events/names.js:12:5)
Sep 26 20:59:44 kourindou lounge[29495]:     at emitOne (events.js:96:13)
Sep 26 20:59:44 kourindou lounge[29495]:     at IrcClient.emit (events.js:188:7)
Sep 26 20:59:44 kourindou lounge[29495]:     at /usr/lib/node_modules/thelounge/node_modules/irc-framework/src/client.js:153:20
Sep 26 20:59:44 kourindou lounge[29495]:     at next (/usr/lib/node_modules/thelounge/node_modules/middleware-handler/index.js:42:18)
Sep 26 20:59:44 kourindou lounge[29495]:     at MiddlewareHandler.handle (/usr/lib/node_modules/thelounge/node_modules/middleware-handler/index.js:64:3)
Sep 26 20:59:44 kourindou lounge[29495]:     at IrcCommandHandler.<anonymous> (/usr/lib/node_modules/thelounge/node_modules/irc-framework/src/client.js:147:34)
```

Numerous desktop and mobile clients are working just fine with this znc connection. Client <-> ZNC encoding is UTF-8, ZNC <-> Server encoding is ISO-2022-JP.

To mitigate this issue I just commented this `user.mode = network.prefixLookup[user.mode];` line. The crash is no more, but nicks with op rights are with `o` prefix, rather than with `@` prefix.

I believe, the lounge misses predefined PREFIX list, if the server doesn't return one.

### PR DESCRIPTION
**Pull request by nornagon**
Fixes #644.

I'm not sure if directly reaching into `irc-framework/src/networkinfo` is a good idea here, but it seems like [irc-fw only creates this object when you call `connect()`](https://github.com/kiwiirc/irc-framework/blob/master/src/client.js#L73), and I don't know of a good way to test that.

### CODE REVIEW

**Comment by astorije** [comment]
I have no idea how that's possible because that file hasn't changed since May, but GitHub says you have conflicts on `src/models/network.js`. Mind rebasing/fixing conflicts?

File: src/models/network.js [hunk 1]
```diff
@@ -1,5 +1,6 @@
 var _ = require("lodash");
 var Chan = require("./chan");
+var NetworkInfo = require("irc-framework/src/networkinfo");
```
Comment (xPaw) [inline src/models/network.js]: Not a fan of requering files like that. I think you can just access the network object in the connect event.

**Comment by nornagon** [comment]
Fair point. I’m not sure how to write a test that calls connect without
actually connecting, though :/

**Comment by xPaw** [comment]
@nornagon tests are not critical to have (in the current state of things anyway).

**Comment by astorije** [comment]
@nornagon, @xPaw, is this PR conflicting with #632? Is it still relevant? Does it need updating?

**Comment by xPaw** [comment]
It doesn't conflict, but it needs updating.

**Comment by nornagon** [comment]
moved code to `"socket connected"` event, dropped test

File: src/plugins/irc-events/connection.js [hunk 2]
```diff
@@ -48,6 +48,11 @@ module.exports = function(irc, network) {
 	});
 
 	irc.on("socket connected", function() {
+		network.prefixLookup = {};
+		_.each(irc.network.options.PREFIX, function(mode) {
```
Comment (astorije) [inline src/plugins/irc-events/connection.js]: Might be a nitpick, but any reason to use Lodash's `.each` instead of native `forEach`?

Comment (nornagon) [inline src/plugins/irc-events/connection.js]: nope, no reason. fixed.

Comment (xPaw) [inline src/plugins/irc-events/connection.js]: You fixed it in the wrong place 😁

Comment (nornagon) [inline src/plugins/irc-events/connection.js]: gah, haha.

Comment (nornagon) [inline src/plugins/irc-events/connection.js]: fixed for real this time

**Comment by astorije** [comment]
Hey @nornagon, we have free sticker packs for our contributors now!
If you're interested, go fill the form at https://goo.gl/forms/f5usqAEp5DWoeXC92 🙂
